name: Docker Image for all neon tests

on:
  push:
    branches:
      - develop
      - '[vt][0-9].[0-9]+.[0-9x]+*'
  workflow_dispatch:
    inputs:
      oz_tag:
        type: string
        required: false
        description: "Which OZ tag to use (if it is empty 'latest', branch will be used)"

jobs:
  dockerize:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Define env
        id: define-env
        run: |
            if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_name }}" == 'develop'  ]]; then
                tag='latest'
                oz_tag='latest'
            elif [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.ref_name }}" == 'develop' && ( "${{ github.event.inputs.oz_tag }}" == 'latest' || "${{ github.event.inputs.oz_tag }}" == "" ) ]]; then
                tag='latest'
                oz_tag='latest'
            elif [[ "${{ github.event.inputs.oz_tag }}" != "" ]]; then
                tag='${{ github.event.inputs.oz_tag }}'
                oz_tag='${{ github.event.inputs.oz_tag }}'
            else
                tag='${{ github.sha }}'
                oz_tag='latest'
            fi
            echo "tag=${tag}"
            echo "oz_tag=${oz_tag}"
            echo "tag=${tag}" >> $GITHUB_OUTPUT
            echo "oz_tag=${oz_tag}" >> $GITHUB_OUTPUT
      - name: "Dockerize neon tests"
        uses: ./.github/actions/dockerize-neon-tests
        with:
          image_tag: ${{ steps.define-env.outputs.tag }}
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          oz_tag: ${{ steps.define-env.outputs.oz_tag }}
