name: "The Graph tests"

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

env:
  DEVNET_FAUCET_URL: ${{ secrets.DEVNET_FAUCET_URL }}
  DEVNET_SOLANA_URL: ${{ secrets.SOLANA_URL }}

jobs:
  tests:
    runs-on: ubuntu-20.04
    name: The Graph tests
    steps:
      - uses: actions/checkout@v4
      - name: Install python requirements
        id: requirements
        uses: ./.github/actions/python-requirements

      - name: Prepare accounts
        env:
          NETWORK: devnet
        id: accounts
        run: |
          python3 ./clickfile.py infra gen-accounts -c 3 -a 10000 -n ${{ env.NETWORK }}
      - name: Trigger the Graph tests
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GHTOKEN }}
          repository: neonlabsorg/graph-node
          event-type: integration-tests
          client-payload: '{"accounts": "${{ env.ACCOUNTS }}"}'
